### ISSUE TITLE
pry-moves releases are actually pry-nav

### ISSUE THREAD

**Issue by nilbus** [garmoshka-mo/pry-moves#11]
Since this is a fork, pry-moves' [releases page][] lists old releases from pry-nav. The most recent is from 2014, which gives the false impression that pry-moves is an old, inactive project.

[Releases page]: https://github.com/garmoshka-mo/pry-moves/releases

I'd recommend you delete each of the existing releases by visiting each release's page (e.g. [v0.2.4][]) and clicking Delete.

It would also be helpful for you to create releases for your own versions, either by pushing tags or by drafting a new release at the [Releases page][].

[v0.2.4]: https://github.com/garmoshka-mo/pry-moves/releases/tag/v0.2.4

Thanks!

**Comment by garmoshka-mo** [comment]
Good catch :+1: Thank you for detailed instructions, done
