### ISSUE TITLE
require 'pry' instead of require 'pry-moves' causes an error

### ISSUE THREAD

**Issue by EthanZeigler** [garmoshka-mo/pry-moves#13]
Not using rails, when requiring 'pry' instead of 'pry-moves' causes `undefined method 'pry' for class Binding` to be raised. This isn't mentioned in the readme and really should be.

**Comment by garmoshka-mo** [comment]
This gem (pry-moves) should be required with `'pry-moves'`. `pry` - is other library

Readme already has: 

> For non-rails (without auto-require), add to your script: require 'pry-moves'
