### ISSUE TITLE
Does not support the latest version of pry (0.11.3)

### ISSUE THREAD

**Issue by fabioperrella** [garmoshka-mo/pry-moves#2]
Hi!

this gem can be used only with pry < 0.11.0

What about accepting 0.11.x ?

**Comment by fabioperrella** [comment]
please, could add the label `Hacktoberfest` to this issue?

You can learn more about this at https://hacktoberfest.digitalocean.com/

**Comment by garmoshka-mo** [comment]
thank you, @fabioperrella 👍
